name = "FixedTargetBackgrounds"
uuid = "1dba36dd-64f4-4bc3-b738-133cf09736d3"
authors = ["Alexander Moreno Briceño <alexander.moreno@uan.edu.co> and contributors"]
version = "1.0.0-DEV"

[compat]
julia = "1.12"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
