name = "FixedTargetBackgrounds"
uuid = "1dba36dd-64f4-4bc3-b738-133cf09736d3"
version = "1.0.0-DEV"
authors = ["Alexander Moreno Briceño <alexander.moreno@uan.edu.co> and contributors"]

[deps]
PYTHIA8 = "ab9774ad-7527-4370-92ef-86b02700ecc9"

[weakdeps]
Makie = "ee78f7c6-11fb-53f2-987a-cfe4a2b5a57a"

[extensions]
FixedTargetBackgroundsMakieExt = "Makie"

[compat]
PYTHIA8 = "0.2.3"
julia = "1.12"
Makie = "0.21, 0.22, 0.23"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
